# PostgreSQL driver
gem 'pg'

# Sinatra driver
gem 'sinatra'
gem 'sinatra-contrib'

# Use Thin for our web server
gem 'thin'

gem 'activesupport'
gem 'activerecord'

gem 'rake'

gem 'shotgun'

gem 'bcrypt', '~> 3.1.7'
gem 'bcrypt-ruby', '~> 3.0.0'

group :test do
  gem 'shoulda-matchers'
  gem 'rack-test'
  gem 'rspec'
end

group :test, :development do
  gem 'factory_girl'
  gem 'faker'
end
